[package]
authors     = ["Braden Steffaniak"]
description = "Free logging library"
edition     = "2021"
license     = "MPL-2.0"
name        = "free_log"
version     = "0.4.1"

[dependencies]
free_log_client = { version = "0.4.1", path = "../rust-client" }
free_log_models = { version = "0.2.0", path = "../models" }
free_log_writer = { version = "0.2.0", path = "../writer" }

[features]
fail-on-warnings = []
