[package]
authors     = ["Braden Steffaniak"]
description = "Free logging library shared models"
edition     = "2021"
license     = "MPL-2.0"
name        = "free_log_models"
version     = "0.1.0"

[dependencies]
log          = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
strum        = { workspace = true }
strum_macros = { workspace = true }
thiserror    = { workspace = true }

[features]
fail-on-warnings = []
