[workspace]
members  = ["packages/writer"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
actix-cors        = "0.6.4"
actix-files       = "0.6.2"
actix-web         = "4.4.0"
awc               = "3.0.0-beta.9"
env_logger        = "0.10"
lambda-web        = { version = "0.2.1", features = ["actix4"] }
lambda_runtime    = "0.8.2"
log               = { version = "0.4", features = ["release_max_level_trace"] }
pretty_env_logger = "0.4"
serde             = { version = "1.0", features = ["derive"] }
serde_json        = "1.0.107"
thiserror         = "1.0.48"
