[workspace]
members  = ["packages/writer"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
actix-cors         = "0.6.5"
actix-files        = "0.6.5"
actix-web          = "4.5.1"
awc                = "3.4.0"
aws-config         = { version = "1.1.6", features = ["behavior-version-latest"] }
aws-sdk-cloudwatch = "1.16.0"
env_logger         = "0.10"
lambda-web         = { version = "0.2.1", features = ["actix4"] }
lambda_runtime     = "0.8.3"
log                = { version = "0.4", features = ["release_max_level_trace"] }
pretty_env_logger  = "0.4"
serde              = { version = "1.0", features = ["derive"] }
serde_json         = "1.0.114"
thiserror          = "1.0.57"
