[workspace]
members = [
    "packages/free-log",
    "packages/models",
    "packages/rust-client",
    "packages/writer",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
actix-cors = "0.7.0"
actix-files = "0.6.6"
actix-web = "4.9.0"
awc = "3.5.1"
aws-config = { version = "1.5.6", features = ["behavior-version-latest"] }
aws-sdk-cloudwatch = "1.47.0"
aws-sdk-cloudwatchlogs = "1.48.0"
aws-smithy-runtime-api = "1.7.2"
derive_builder = "0.20.1"
env_logger = "0.11"
futures-util = { version = "0.3.30", default-features = false, features = [
    "std",
] }
lambda-web = { version = "0.2.1", features = ["actix4"] }
lambda_runtime = "0.13.0"
log = { version = "0.4", features = ["release_max_level_trace"] }
once_cell = { version = "1.20.0" }
pretty_env_logger = "0.5"
reqwest = { version = "0.12.7", default-features = false, features = [
    "blocking",
    "stream",
    "rustls-tls",
    "json",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.128"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["sync", "io-util"] }
tokio-stream = "0.1.16"
tokio-util = "0.7.12"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
