[package]
authors = ["Braden Steffaniak"]
edition = "2021"
name    = "log_service_writer"
version = "0.1.0"

[dependencies]
actix-cors             = { workspace = true }
actix-files            = { workspace = true }
actix-web              = { workspace = true }
awc                    = { workspace = true }
aws-config             = { workspace = true }
aws-sdk-cloudwatchlogs = { workspace = true }
env_logger             = { workspace = true }
lambda-web             = { workspace = true }
lambda_runtime         = { workspace = true }
log                    = { workspace = true }
once_cell              = { workspace = true }
serde                  = { workspace = true }
serde_json             = { workspace = true }
strum                  = { workspace = true }
strum_macros           = { workspace = true }
thiserror              = { workspace = true }

[features]
fail-on-warnings = []
