[package]
authors     = ["Braden Steffaniak"]
description = "Free logging library log writer"
edition     = "2021"
license     = "MPL-2.0"
name        = "free_log_writer"
version     = "0.1.0"

[dependencies]
free_log_models = { version = "0.1.0", path = "../models" }

actix-cors             = { workspace = true }
actix-files            = { workspace = true }
actix-web              = { workspace = true }
awc                    = { workspace = true }
aws-config             = { workspace = true }
aws-sdk-cloudwatchlogs = { workspace = true }
aws-smithy-runtime-api = { workspace = true }
env_logger             = { workspace = true }
lambda-web             = { workspace = true }
lambda_runtime         = { workspace = true }
log                    = { workspace = true }
once_cell              = { workspace = true }
serde                  = { workspace = true }
serde_json             = { workspace = true }
strum                  = { workspace = true }
strum_macros           = { workspace = true }
thiserror              = { workspace = true }

[features]
fail-on-warnings = []
